In [3]:
import numpy as np
import pandas as pd
from sklearn import datasets as ds
from sklearn import preprocessing as pp

In [173]:
df = pd.read_csv("/content/drive/MyDrive/中興大學-資料探勘/openpowerlifting.csv")
df.head(10)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (35) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


Name Sex Event Equipment   Age AgeClass Division  BodyweightKg  \
0      Abbie Murphy   F   SBD     Wraps  29.0    24-34     F-OR          59.8   
1       Abbie Tuong   F   SBD     Wraps  29.0    24-34     F-OR          58.5   
2    Ainslee Hooper   F     B       Raw  40.0    40-44     F-OR          55.4   
3   Amy Moldenhauer   F   SBD     Wraps  23.0    20-23     F-OR          60.0   
4      Andrea Rowan   F   SBD     Wraps  45.0    45-49     F-OR         104.0   
5     April Alvarez   F   SBD     Wraps  37.0    35-39     F-OR          74.0   
6        Ash Morgan   F   SBD     Wraps  23.0    20-23     F-OR          59.8   
7   Belinda Moloney   F   SBD     Wraps  35.0    35-39     F-OR          80.4   
8   Briony Williams   F   SBD     Wraps  36.0    35-39     F-OR         108.0   
9  Brooke Kowalczyk   F   SBD     Wraps  37.0    35-39     F-OR          74.8   

  WeightClassKg  Squat1Kg  Squat2Kg  Squat3Kg  Squat4Kg  Best3SquatKg  \
0            60      80.0      92.5     105.0       NaN         105.0   
1            60     100.0     110.0     120.0       NaN         120.0   
2            56       NaN       NaN       NaN       NaN           NaN   
3            60    -105.0    -105.0     105.0       NaN         105.0   
4           110     120.0     130.0     140.0       NaN         140.0   
5            75     127.5     135.0     142.5       NaN         142.5   
6            60     115.0     125.0    -135.0       NaN         125.0   
7          82.5     120.0     130.0     140.0       NaN         140.0   
8           110     180.0     200.0     220.0       NaN         220.0   
9            75     180.0     190.0     200.0       NaN         200.0   

   Bench1Kg  Bench2Kg  Bench3Kg  Bench4Kg  Best3BenchKg  Deadlift1Kg  \
0      45.0      50.0      55.0       NaN          55.0        110.0   
1      55.0      62.5      67.5       NaN          67.5        130.0   
2      27.5      32.5     -35.0       NaN          32.5          NaN   
3      67.5      72.5     -75.0       NaN          72.5        132.5   
4      70.0      75.0      80.0       NaN          80.0        150.0   
5      72.5      77.5      82.5       NaN          82.5        125.0   
6      65.0      70.0     -75.0       NaN          70.0        130.0   
7      67.5      72.5      77.5       NaN          77.5        125.0   
8      90.0     100.0       NaN       NaN         100.0        200.0   
9      90.0      95.0     -97.5       NaN          95.0        160.0   

   Deadlift2Kg  Deadlift3Kg  Deadlift4Kg  Best3DeadliftKg  TotalKg Place  \
0        120.0        130.0          NaN            130.0    290.0     4   
1        140.0        145.0          NaN            145.0    332.5     2   
2          NaN          NaN          NaN              NaN     32.5     1   
3       -140.0       -140.0          NaN            132.5    310.0     3   
4        160.0        170.0          NaN            170.0    390.0     3   
5        135.0        145.0          NaN            145.0    370.0     5   
6        140.0        150.0          NaN            150.0    345.0     1   
7        140.0        152.5          NaN            152.5    370.0     5   
8          NaN          NaN          NaN            200.0    520.0     1   
9        170.0        180.0          NaN            180.0    475.0     1   

    Wilks  McCulloch  Glossbrenner  IPFPoints Tested Country Federation  \
0  324.16     324.16        286.42     511.15    NaN     NaN    GPC-AUS   
1  378.07     378.07        334.16     595.65    NaN     NaN    GPC-AUS   
2   38.56      38.56         34.12     313.97    NaN     NaN    GPC-AUS   
3  345.61     345.61        305.37     547.04    NaN     NaN    GPC-AUS   
4  321.25     338.91        274.56     550.08    NaN     NaN    GPC-AUS   
5  354.74     354.74        312.20     596.18    NaN     NaN    GPC-AUS   
6  385.63     385.63        340.74     612.23    NaN     NaN    GPC-AUS   
7  337.62     337.62        296.00     575.85    NaN     NaN    GPC-AUS   
8  424.49     

In [174]:
df.columns

Index(['Name', 'Sex', 'Event', 'Equipment', 'Age', 'AgeClass', 'Division',
       'BodyweightKg', 'WeightClassKg', 'Squat1Kg', 'Squat2Kg', 'Squat3Kg',
       'Squat4Kg', 'Best3SquatKg', 'Bench1Kg', 'Bench2Kg', 'Bench3Kg',
       'Bench4Kg', 'Best3BenchKg', 'Deadlift1Kg', 'Deadlift2Kg', 'Deadlift3Kg',
       'Deadlift4Kg', 'Best3DeadliftKg', 'TotalKg', 'Place', 'Wilks',
       'McCulloch', 'Glossbrenner', 'IPFPoints', 'Tested', 'Country',
       'Federation', 'Date', 'MeetCountry', 'MeetState', 'MeetName'],
      dtype='object')

In [175]:
pd.set_option('display.max_columns',37)
df.head(10)

Name Sex Event Equipment   Age AgeClass Division  BodyweightKg  \
0      Abbie Murphy   F   SBD     Wraps  29.0    24-34     F-OR          59.8   
1       Abbie Tuong   F   SBD     Wraps  29.0    24-34     F-OR          58.5   
2    Ainslee Hooper   F     B       Raw  40.0    40-44     F-OR          55.4   
3   Amy Moldenhauer   F   SBD     Wraps  23.0    20-23     F-OR          60.0   
4      Andrea Rowan   F   SBD     Wraps  45.0    45-49     F-OR         104.0   
5     April Alvarez   F   SBD     Wraps  37.0    35-39     F-OR          74.0   
6        Ash Morgan   F   SBD     Wraps  23.0    20-23     F-OR          59.8   
7   Belinda Moloney   F   SBD     Wraps  35.0    35-39     F-OR          80.4   
8   Briony Williams   F   SBD     Wraps  36.0    35-39     F-OR         108.0   
9  Brooke Kowalczyk   F   SBD     Wraps  37.0    35-39     F-OR          74.8   

  WeightClassKg  Squat1Kg  Squat2Kg  Squat3Kg  Squat4Kg  Best3SquatKg  \
0            60      80.0      92.5     105.0       NaN         105.0   
1            60     100.0     110.0     120.0       NaN         120.0   
2            56       NaN       NaN       NaN       NaN           NaN   
3            60    -105.0    -105.0     105.0       NaN         105.0   
4           110     120.0     130.0     140.0       NaN         140.0   
5            75     127.5     135.0     142.5       NaN         142.5   
6            60     115.0     125.0    -135.0       NaN         125.0   
7          82.5     120.0     130.0     140.0       NaN         140.0   
8           110     180.0     200.0     220.0       NaN         220.0   
9            75     180.0     190.0     200.0       NaN         200.0   

   Bench1Kg  Bench2Kg  Bench3Kg  Bench4Kg  Best3BenchKg  Deadlift1Kg  \
0      45.0      50.0      55.0       NaN          55.0        110.0   
1      55.0      62.5      67.5       NaN          67.5        130.0   
2      27.5      32.5     -35.0       NaN          32.5          NaN   
3      67.5      72.5     -75.0       NaN          72.5        132.5   
4      70.0      75.0      80.0       NaN          80.0        150.0   
5      72.5      77.5      82.5       NaN          82.5        125.0   
6      65.0      70.0     -75.0       NaN          70.0        130.0   
7      67.5      72.5      77.5       NaN          77.5        125.0   
8      90.0     100.0       NaN       NaN         100.0        200.0   
9      90.0      95.0     -97.5       NaN          95.0        160.0   

   Deadlift2Kg  Deadlift3Kg  Deadlift4Kg  Best3DeadliftKg  TotalKg Place  \
0        120.0        130.0          NaN            130.0    290.0     4   
1        140.0        145.0          NaN            145.0    332.5     2   
2          NaN          NaN          NaN              NaN     32.5     1   
3       -140.0       -140.0          NaN            132.5    310.0     3   
4        160.0        170.0          NaN            170.0    390.0     3   
5        135.0        145.0          NaN            145.0    370.0     5   
6        140.0        150.0          NaN            150.0    345.0     1   
7        140.0        152.5          NaN            152.5    370.0     5   
8          NaN          NaN          NaN            200.0    520.0     1   
9        170.0        180.0          NaN            180.0    475.0     1   

    Wilks  McCulloch  Glossbrenner  IPFPoints Tested Country Federation  \
0  324.16     324.16        286.42     511.15    NaN     NaN    GPC-AUS   
1  378.07     378.07        334.16     595.65    NaN     NaN    GPC-AUS   
2   38.56      38.56         34.12     313.97    NaN     NaN    GPC-AUS   
3  345.61     345.61        305.37     547.04    NaN     NaN    GPC-AUS   
4  321.25     338.91        274.56     550.08    NaN     NaN    GPC-AUS   
5  354.74     354.74        312.20     596.18    NaN     NaN    GPC-AUS   
6  385.63     385.63        340.74     612.23    NaN     NaN    GPC-AUS   
7  337.62     337.62        296.00     575.85    NaN     NaN    GPC-AUS   
8  424.49     

In [182]:
SBD = pd.DataFrame(data=df,columns=['Federation']+['Name']+['Sex']+['Event']+['Age']+['Equipment']+['BodyweightKg']+['Best3SquatKg']+['Best3BenchKg']+['Best3DeadliftKg']+['TotalKg'])
SBD = SBD.fillna(value=0)

In [183]:
SBD = SBD[SBD["Equipment"].isin(["Raw"])]
SBD = SBD[SBD["Event"].isin(["SBD"])]
#SBD = SBD[SBD["Sex"].isin(["M"])]
SBD = SBD[SBD['Federation'].isin(["IPF"])]
SBD.head(10)

Federation                           Name Sex Event   Age Equipment  \
88751         IPF              Andrzej Stanaszek   M   SBD  19.5       Raw   
102152        IPF              Andrzej Stanaszek   M   SBD  20.5       Raw   
106855        IPF              Andrzej Stanaszek   M   SBD  21.5       Raw   
111083        IPF              Andrzej Stanaszek   M   SBD  22.5       Raw   
113557        IPF              Andrzej Stanaszek   M   SBD  23.5       Raw   
138022        IPF              Andrzej Stanaszek   M   SBD  18.5       Raw   
767259        IPF          María Guðsteinsdóttir   F   SBD  48.5       Raw   
767260        IPF                    Joy Nnamani   F   SBD  26.5       Raw   
767261        IPF  Ragnheiður Kr. Sigurðardóttir   F   SBD  37.5       Raw   
767262        IPF         Arna Ösp Gunnarsdóttir   F   SBD  23.5       Raw   

        BodyweightKg  Best3SquatKg  Best3BenchKg  Best3DeadliftKg  TotalKg  
88751          47.80         217.5         155.0            125.0    497.5  
102152         49.50         247.5         162.5            125.0    535.0  
106855         51.45         252.5         172.5            142.5    567.5  
111083         50.60         270.0         177.5            130.0    577.5  
113557         49.90         250.0         172.5            145.0    567.5  
138022         50.30         190.0         135.0            120.0    445.0  
767259         52.00          87.5          65.0            150.0    302.5  
767260         57.00         160.0          90.0            203.0    453.0  
767261         56.80         132.5          82.5            152.5    367.5  
767262         61.70         122.5          75.0            172.5    370.0

In [178]:
SBD.isnull().sum()

Federation         0
Name               0
Sex                0
Event              0
Age                0
Equipment          0
BodyweightKg       0
Best3SquatKg       0
Best3BenchKg       0
Best3DeadliftKg    0
TotalKg            0
dtype: int64

In [144]:
SBD.to_csv('SBD.CSV')

In [88]:
import csv 
import numpy as np

file_name = "/content/SBD.CSV" 
f = open(file_name,'r')
data = np.array([row for row in csv.reader(f)])
f.close

<function TextIOWrapper.close()>

In [92]:
for dt in data[:15,:10]:
  print(dt)

['' 'Federation' 'Name' 'Sex' 'Event' 'Age' 'Equipment' 'BodyweightKg'
 'Best3SquatKg' 'Best3BenchKg']
['41' 'GPC-AUS' 'Adrian Zwaan' 'M' 'SBD' '80.0' 'Raw' '82.1' '100.0'
 '72.5']
['49' 'GPC-AUS' 'Ben Hales' 'M' 'SBD' '31.0' 'Raw' '98.6' '187.5' '115.0']
['54' 'GPC-AUS' 'Brady Curtin' 'M' 'SBD' '21.0' 'Raw' '88.1' '170.0'
 '115.0']
['74' 'GPC-AUS' 'Griffin Spence' 'M' 'SBD' '27.0' 'Raw' '67.1' '182.5'
 '107.5']
['84' 'GPC-AUS' 'Jim Collins' 'M' 'SBD' '72.0' 'Raw' '82.5' '105.0' '75.0']
['86' 'GPC-AUS' 'John Wallin' 'M' 'SBD' '47.0' 'Raw' '117.7' '240.0'
 '175.0']
['881' 'GPC-AUS' 'Frank Day' 'M' 'SBD' '24.0' 'Raw' '77.1' '162.5' '112.5']
['886' 'GPC-AUS' 'Lex Anderson' 'M' 'SBD' '62.0' 'Raw' '65.5' '140.0'
 '97.5']
['888' 'GPC-AUS' 'Matt Pearce' 'M' 'SBD' '24.0' 'Raw' '65.4' '160.0'
 '120.0']
['927' 'GPC-AUS' 'Griffin Spence' 'M' 'SBD' '26.0' 'Raw' '66.8' '155.0'
 '105.0']
['987' 'GPC-AUS' 'Chris Iwanowski' 'M' 'SBD' '23.0' 'Raw' '138.9' '300.0'
 '160.0']
['1673' 'GPC-AUS' 'CJ Mendoza

In [245]:
SBD_2 = pd.DataFrame(data=SBD,columns=['BodyweightKg']+['Best3SquatKg']+['Best3BenchKg']+['Best3DeadliftKg'])
SBD_2.head(10)

BodyweightKg  Best3SquatKg  Best3BenchKg  Best3DeadliftKg
88751          47.80         217.5         155.0            125.0
102152         49.50         247.5         162.5            125.0
106855         51.45         252.5         172.5            142.5
111083         50.60         270.0         177.5            130.0
113557         49.90         250.0         172.5            145.0
138022         50.30         190.0         135.0            120.0
767259         52.00          87.5          65.0            150.0
767260         57.00         160.0          90.0            203.0
767261         56.80         132.5          82.5            152.5
767262         61.70         122.5          75.0            172.5

In [246]:
print(SBD_2.mean())
scale = pp.scale(SBD_2)
scale[:10]

BodyweightKg        80.061008
Best3SquatKg       181.680098
Best3BenchKg       117.709838
Best3DeadliftKg    204.948368
dtype: float64


array([[-1.28365039,  0.50917915,  0.74632056, -1.16336314],
       [-1.21600818,  0.93562851,  0.89642461, -1.16336314],
       [-1.1384186 ,  1.00670341,  1.09656334, -0.9087131 ],
       [-1.1722397 ,  1.25546554,  1.1966327 , -1.09060598],
       [-1.20009237,  0.97116596,  1.09656334, -0.87233452],
       [-1.18417656,  0.11826723,  0.34604311, -1.23612029],
       [-1.11653435, -1.33876811, -1.05492799, -0.79957737],
       [-0.9175867 , -0.30818214, -0.55458117, -0.02835155],
       [-0.9255446 , -0.69909406, -0.70468521, -0.76319879],
       [-0.7305759 , -0.84124385, -0.85478926, -0.47217018]])

In [243]:
pp.normalize(SBD_2)[:10]

array([[0.16000939, 0.72807619, 0.51885889, 0.41843459],
       [0.15222647, 0.76113233, 0.49973335, 0.38441027],
       [0.15075998, 0.73988135, 0.50546349, 0.4175568 ],
       [0.14377169, 0.76716121, 0.50433747, 0.36937392],
       [0.14665611, 0.73475006, 0.50697754, 0.42615503],
       [0.18843433, 0.71177979, 0.50573827, 0.44954513],
       [0.27002423, 0.4543677 , 0.33753029, 0.77891605],
       [0.20388634, 0.57231254, 0.32192581, 0.72612154],
       [0.25189773, 0.58761354, 0.36587258, 0.67630992],
       [0.26503791, 0.52620979, 0.32216926, 0.74098929]])

In [256]:
binarize = pp.binarize(scale)
binarize[:10]

array([[0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [171]:
pp.binarize(scale,threshold=-1)

array([[0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       ...,
       [0., 1., 1., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [198]:
SBD_3 = SBD['Sex']
SBD_3.head(10)

88751     M
102152    M
106855    M
111083    M
113557    M
138022    M
767259    F
767260    F
767261    F
767262    F
Name: Sex, dtype: object

In [248]:
LE = pp.LabelEncoder()
LE.fit(SBD_3)
print(LE.classes_)
print(LE.transform(SBD_3)[:20])

['F' 'M']
[1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1]


In [207]:
!pip Imputer

ERROR: unknown command "Imputer"


In [221]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='median')
imp.fit(SBD_2)
SBD_4 = imp.transform(SBD_2)

In [252]:
SBD_scale = pd.DataFrame(scale,columns=SBD_2.columns)
print(SBD_scale.head(10))
SBD_applymap = SBD_scale.applymap(lambda x: 1 if x > -1 else 0)
print(SBD_applymap.head(10))
transformer = pp.FunctionTransformer(lambda arr:[[y for y in x] for x in arr])

   BodyweightKg  Best3SquatKg  Best3BenchKg  Best3DeadliftKg
0     -1.283650      0.509179      0.746321        -1.163363
1     -1.216008      0.935629      0.896425        -1.163363
2     -1.138419      1.006703      1.096563        -0.908713
3     -1.172240      1.255466      1.196633        -1.090606
4     -1.200092      0.971166      1.096563        -0.872335
5     -1.184177      0.118267      0.346043        -1.236120
6     -1.116534     -1.338768     -1.054928        -0.799577
7     -0.917587     -0.308182     -0.554581        -0.028352
8     -0.925545     -0.699094     -0.704685        -0.763199
9     -0.730576     -0.841244     -0.854789        -0.472170
   BodyweightKg  Best3SquatKg  Best3BenchKg  Best3DeadliftKg
0             0             1             1                0
1             0             1             1                0
2             0             1             1                1
3             0             1             1                0
4             0         

In [253]:
transformer.transform(scale)[:10]

[[-1.283650386413707,
  0.5091791475486829,
  0.746320563174465,
  -1.1633631358349121],
 [-1.2160081827824842,
  0.9356285146833287,
  0.8964246090214175,
  -1.1633631358349121],
 [-1.138418596264317,
  1.0067034092057696,
  1.0965633368173542,
  -0.9087130999249744],
 [-1.1722396980799283,
  1.255465540034313,
  1.1966327007153226,
  -1.0906059827177872],
 [-1.200092370163373,
  0.9711659619445492,
  1.0965633368173542,
  -0.8723345233664118],
 [-1.1841765575442618,
  0.11826722767525753,
  0.3460431075825917,
  -1.2361202889520373],
 [-1.116534353913039,
  -1.3387681100347824,
  -1.054927986988965,
  -0.7995773702492867],
 [-0.9175866961741488,
  -0.3081821394593883,
  -0.5545811674991232,
  -0.028351547207760636],
 [-0.9255446024837045,
  -0.6990940593328137,
  -0.7046852133460757,
  -0.7631987936907242],
 [-0.7305758978995919,
  -0.8412438483776956,
  -0.8547892591930282,
  -0.47217018122222376]]

In [260]:
transformer.transform(pp.binarize(scale))[:10]

[[0.0, 1.0, 1.0, 0.0],
 [0.0, 1.0, 1.0, 0.0],
 [0.0, 1.0, 1.0, 0.0],
 [0.0, 1.0, 1.0, 0.0],
 [0.0, 1.0, 1.0, 0.0],
 [0.0, 1.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0]]